spring.application.name=turfied-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/turfied
spring.datasource.username=postgres
spring.datasource.password=postgres

app.jwt.secret=df0d06f49221af4243ee4894719f415f6b7924a6d47adaf93c3396c64249620b
app.jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true